### ISSUE TITLE
Audio (CRAS client wouldn't connect)

### ISSUE THREAD

**Issue by coelebs** [drinkcat/chroagh#40]
Since a while my sound has stopped working. I tried updating the chroot but it didn't work. When I start alsa mixer it's complaining it can't connect with the CRAS client.

**Comment by Jzarecta** [comment]
Have a similar issue, here is my dump-server info:
utput Devices:
        ID      Name
        6       HDA Intel PCH: ALC283 Analog:1,0
        5       HDA Intel MID: HDMI 2:0,8
        4       HDA Intel MID: HDMI 1:0,7
        3       HDA Intel MID: HDMI 0:0,3
Output Nodes:
         ID     Prio   Vol  Plugged      Time   Type             Name
        6:0        0     0       no 2165526805610496    HEADPHONE       *Headphone
        6:1        1     0      yes 529586647465984     INTERNAL_SPEAKER*Speaker
        5:0        0     0       no          0  HDMI             HDMI/DP,pcm=8 Jack
        4:0        0     0       no          0  HDMI             HDMI/DP,pcm=7 Jack
        3:0        0     0       no 2959073553154048    HDMI            *HDMI/DP,pcm=3 Jack
        3:1        0     0       no          0  HDMI             HDMI
Input Devices:
        ID      Name
        7       HDA Intel PCH: ALC283 Analog:1,0
Input Nodes:
         ID     Prio  Gain  Plugged      Time   Type             Name
        7:0        0     0       no          0  MIC              Mic Jack
        7:1        1     0      yes 531626756931584     INTERNAL_MIC    *Internal Mic
Selected Output Node: 6:1
Selected Input Node: 7:1
Attached clients:
        ID      pid     uid
        1087    10274   1000
Num active streams: 0
Last audio active time: 306887, 495557059
