### ISSUE TITLE
xiwi/criat support for arch

### ISSUE THREAD

**Issue by TylorS** [drinkcat/chroagh#70]
Any idea if/when it might be possible to run arch in a chrome tab? This is definitely something that I would be interested in.

**Comment by drinkcat** [comment]
Yeah. It is planned. There are quite a few other things I want/need to do before I get back to rebasing chroagh to get all the new crouton features...

**Comment by noahleigh** [comment]
When do you think this rebasing will be finished?

**Comment by drinkcat** [comment]
Available now in master, please report if you bump into any issue. Thanks for your patience!
