### ISSUE TITLE
Audio issues.

### ISSUE THREAD

**Issue by Jzarecta** [drinkcat/chroagh#71]
For a while I have been havig audio issues on my chroagh, not sure what caused it. I have tried to restart pulseaudio, use pavucontrol, or alsamixer, nothig seems to work. 

Using mplayer I get:
Audio device got stuck!

Any help on getting my audio back to working mode?

**Comment by drinkcat** [comment]
Have you tried updating your chroot? It's not impossible that it's currently broken, I'll check on my side.

**Comment by Jzarecta** [comment]
Thanks that worked, the update process was a bit cumbersome, would be nice to have the string to update on arch. The original instructions on update intends to download precise. 

This is what I did, although I think some of the flags were no necessary:
`sudo sh -e installer/main.sh -r arch -t xfce -u`

**Comment by drinkcat** [comment]
Well, Arch will get merged into crouton soon, so that'll help ,-)

For reference, the update line looks like this:
```
sudo sh -e installer/main.sh -n arch -u
```
(but, of course, what you did also works)
