### ISSUE TITLE
Can't start any services (not specific to chromebooks, but still an issue)

### ISSUE THREAD

**Issue by kdb424** [drinkcat/chroagh#8]
systemctl can not start services in a chroot. This causes me issues as I need sshi and other services running. I would not have opened an issue had it not been for the fact that the Ubuntu chroot is able to do this without a problem (doesn't use systemctl). If possible, please offer a workaround/solution for this as I have to use an Ubuntu chroot to do some of my work. Thank you very much.

**Comment by Jzarecta** [comment]
I tried doing /usr/bin/sshd however the problem seems to be that there is no port open, this could happened on the ChromeOS iptable layer or somewhere on the chroot setting that disable any communication into any port. 
I tried doing nmap on the ip and got back "Host seems down."

**Comment by drinkcat** [comment]
@Jzarecta : See https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton.

**Comment by tychoish** [comment]
It might be nice to be able to run a systemd --user instance.

**Comment by bendavis78** [comment]
Apparently this can be done with PID namespacing, assuming the stock pixel kernel has this enabled by default: https://wiki.archlinux.org/index.php/Init#systemd-nspawn

We'd need to use jchroot instead of chroot. I haven't tried compiling this on my chromebook yet.
