### ISSUE TITLE
startcli - Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by wulvyrn** [drinkcat/chroagh#86]
i used this to create the chroot
sudo sh -e installer/main.sh -r arch -n arch.cli-extra -t cli-extra

when i try "sudo startcli", it gives me this error

Entering /mnt/stateful_partition/crouton/chroots/arch.cli-extra...
Couldn't get a file descriptor referring to the console
Unmounting /mnt/stateful_partition/crouton/chroots/arch.cli-extra...

sudo enter-chroot #works fine

**Comment by drewfish** [comment]
I have this problem too. Just installed crouton -t cli-extra on an Asus CN60.

**Comment by drewfish** [comment]
BTW, should this issue perhaps be filed on the parent repository (dnschneid/crouton)?
