### ISSUE TITLE
xiwi not found

### ISSUE THREAD

**Issue by wulvyrn** [drinkcat/chroagh#87]
i installed the chroot with
sudo sh -e installer/main.sh -r arch -n arch.xiwi -t xiwi,lxde

it fails to launch in a tab when i try
sudo enter-chroot -n arch.xiwi xiwi -T xterm
Entering /mnt/stateful_partition/crouton/chroots/arch.xiwi...
xiwi: xterm: not found
Unmounting /mnt/stateful_partition/crouton/chroots/arch.xiwi...

xterm is installed but xiwi is not in /usr/local/bin
i tried a precise install with crouton and xiwi is in /usr/local/bin

any ideas?

**Comment by rperce** [comment]
Try to do a normal `sudo enter-chroot` and then just `xinit` from the shell inside.
