### ISSUE TITLE
crispy console switching

### ISSUE THREAD

**Issue by DennisLfromGA** [drinkcat/chroagh#98]
With the implementation of 'frecon' and the removal of VTs (and switching via chvt), the creation of a crispy (ChRoots In a Separate Partition - Yay!) crouton via the '-S' option no longer works. 

Is there any plan to accommodate frecon in this branch and eventually merge it with crouton ?

Thanx for your consideration,
-DennisL

**Comment by DennisLfromGA** [comment]
It's dead Jim!

**Comment by drinkcat** [comment]
Well, it can be revived by anyone with enough time to work on that!
